# For GitHub user:
# github_username: "slack_member_id"
# For GitHub team:
# github_teamname: "slack_member_id"

# Team
manishapriya94: 'U014PTUCF45'
JamesMGreene: 'U020NHEBUPM'
DietBepis1: 'U03K6HNBNNP'
thyeggman: 'U03JUQDB8CB'
paramsiddharth: 'U03J5KZVDM3'
eprice555: 'U03UZQDA5DL'
wallace: 'U02M9M81WUS'
gdomingu: 'U03JVS4G334'
ipc103: 'U046UL9BS9M'
therzka: 'U03V8PPKR6H'
joeyouss: 'U043YKQND98'

# Fellows
tdo95: 'U0457B11TLY'
ahn-nath: 'U043EMMAK9S'
rcmtcristian: 'U044N2XMGSC'
LoopFruits: 'U03A63J8U4V'
ericvennemeyer: 'U04354QA2K0'
sammychinedu2ky: 'U042T8UV7GF'
JoseEspinosaMachado: 'U043XLVG5R9'
Alex-is-Gonzalez: 'U04NASJJ5R6'
rsensenig: 'U04LD85GHDH'
SAUMILDHANKAR: 'U04MG19LM7G'
beverand: 'U04M9E6CXHS'
yoyoyojoe: 'U04LSCZPGF9'
christina-ml: 'U04M0BU9GCE'
