name: Cats

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  contents: read

jobs:
  aCatForCreatingThePullRequest:
    name: A cat for your effort!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Action Cats
      - uses: ruairidhwm/action-cats@1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
