require('dotenv').config()
const express = require('express')
const cors = require('cors')
const web = express()
const api = express()
const rateLimit = require('express-rate-limit')

// Routes generated by Vue CLI
const path = __dirname + '/views/';
web.use(express.static(path));

web.get('/', function (req,res) {
  res.sendFile(path + "index.html");
});

// Middleware
api.use(express.json())
api.use(cors())

// Rate Limiting
// Enable if you're behind a reverse proxy (Heroku, Bluemix, AWS ELB or API Gateway, Nginx, etc)
// see https://expressjs.com/en/guide/behind-proxies.html
api.set('trust proxy', true)

// to unblock for now
const apiLimiter = rateLimit({
  windowMs: 1 * 60 * 1000, // 1 minutes
  max: 100000
})

// only apply to requests that begin with /api/
api.use('/api', apiLimiter)
const representatives = require('./routes/api/representatives')
const campaigns = require('./routes/api/campaigns')
const authentication = require('./routes/api/authentication')
const letter_versions = require('./routes/api/letter_versions')
const lob = require('./routes/api/lob')
const checkout = require('./routes/api/checkout')
// const give = require('./routes/api/give');

// const email = require('./routes/api/email')


api.use('/api/representatives', representatives)
api.use('/api/campaigns', campaigns)
api.use('/api/authentication', authentication)
api.use('/api/letter_versions', letter_versions)
api.use('/api/lob', lob)
api.use('/api/checkout', checkout)
// app.use('/api/give', give);
// app.use('/api/library', library);
// app.use('/api/email', email);

module.exports = {api, web}
