const path = require('path')
const express = require('express')
const history = require('connect-history-api-fallback')
const apiRouter = require('./api')
const authRouter = require('./routes/api/authentication')

const app = express()

// Enable if you're behind a reverse proxy (Heroku, Bluemix, AWS ELB or API Gateway, Nginx, etc)
// see https://expressjs.com/en/guide/behind-proxies.html
app.set('trust proxy', true)

// Load the API router
app.use('/api', apiRouter)

// Load the authentication router
app.use('/api/v1/auth', authRouter)

// Fix for hash URLs in Vue
// IMPORTANT: MUST be added before the `express.static` middleware for the `dist/` directory
app.use(history())

// Routes generated by Vue CLI
const staticPath = path.resolve(__dirname, '../dist')
app.use(express.static(staticPath, { maxAge: '1d', etag: false }))

module.exports = app
