# Update 'VARIANT' to pick a default version of Node.js: 16, 14, 12.
# Append -bullseye to pin to local arm64/Apple Silicon.
# Append -buster to pin to Debian.
ARG VARIANT=16-buster

FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}
