name: Create Calendar Event

on: [push]

jobs:
  create-event:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Create Event using Ms. Graph
    steps:
      - name: Print a message if client id exist
        env:
          clientId: ${{ secrets.CLIENT_ID }}
        run: |
          if [ -n "${{ secrets.CLIENT_ID }}" ] ; then
            echo "Client ID exist and value is ${{ secrets.CLIENT_ID }}"
          else
            echo "Client ID is not found"
          fi

      - name: Message dump
        run: echo '${{ toJSON(github.event) }}' | jq

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create event on the next day
        uses: JulieGunawan/ms-graph-create-event-msal@main
        env:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          tenantId: ${{ secrets.TENANT_ID }}
        with:
          clientId: clientId
          clientSecret: clientSecret
          tenantId: tenantId
          subject: 'Did you get the event?'
          body: 'Some files have been pushed on ${{ github.repository }} from ${{ github.actor }}. Please find the details here ${{ github.event.compare }}.'
          userEmail: 'yetty.gunawan@edu.sait.ca'
          start: '2023-11-25T14:30:00'
          end: '2023-11-25T15:00:00'
