name: Spell Check .md
on:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'
permissions:
  contents: read
  pull-requests: write
  actions: write
  checks: write
  issues: write

jobs:
  spellcheck:
    uses: austenstone/spellchecker-cli-action-summary/.github/workflows/spellcheck.yml@main
